### ISSUE TITLE
Improve LIKE error message

### ISSUE THREAD

**Issue by redcatbear** [exasol/virtual-schema-common-document#159]
## Situation

When using `LIKE` on any other column than `SOURCE_REFERENCE`,  users get the following error message:

>  F-VSD-5: The current version of virtual-schemas does not support LIKE and NOT LIKE as post-selection. Please change your query. 

While technically true, that error message is confusing. What it should do instead is:

1. State that `LIKE` is only supported on the `SOURCE_REFERENCE` column.
2. Explain why (efficiency)
3. Explain what users can do to mitigate the situation (wrap in a super-select that does the `LIKE`)

**Comment by exaSR** [comment]
Hmm... as the adapter should know it is creating SQL for Exasol... can it not simply wrap itself into a 
```sql
select * from ( import ) where <LIKE>
```
?

**Comment by redcatbear** [comment]
No. That would require an SQL engine in the adapter.
