### ISSUE TITLE
Auto Inference should keep original column names

### ISSUE THREAD

**Issue by tm-henningnt** [exasol/virtual-schema-common-document#189]
Auto inference should have an option keep the original column names instead of always changing them to UPPER_SNAKE_CASE. The conversion is only mentioned for CSV files, so it happening for Parquet files also may be a bug.

**Comment by ckunki** [comment]
uppercase and lowercase characters will be possible, I guess.
In general: The implementation should take care to meet the requirements for valid column names in Exasol database.

**Comment by kaklakariada** [comment]
Naming conventions for SQL Identifiers: https://docs.exasol.com/db/latest/sql_references/basiclanguageelements.htm#SQLIdentifier

**Comment by kaklakariada** [comment]
This feature must be implemented in https://github.com/exasol/virtual-schema-common-document-files, not here. So I created https://github.com/exasol/virtual-schema-common-document-files/issues/163.
